### PR TITLE
Provide support for webpack 4 and support compatibility with version 3

### PR DESCRIPTION
**Pull request by macku**
After upgrading both webpack to version 4 and plugin to the latest version, there are some issues with using the new plugin system:

```
ERROR in   TypeError: Cannot read property 'publicPath' of undefined

  - index.js:236
    [project]/[html-webpack-include-assets-plugin]/index.js:236:34


  - new Promise


  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [project]/[tapable]/lib/Hook.js:35:21

  - index.js:647
    [project]/[html-webpack-plugin]/index.js:647:47

  - index.js:162 Promise.resolve.then.then.then.then.compilationResult
    [project]/[html-webpack-plugin]/index.js:162:36

```

In order to support both webpack 3 and webpack 4 we need to use the [new plugins API](https://blog.johnnyreilly.com/2018/01/finding-webpack-4-use-map.html).

### CODE REVIEW

**Comment by macku** [comment]
It's easier to check the changes [without whitepsaces diff](https://github.com/jharris4/html-webpack-include-assets-plugin/pull/23/files?w=1)

**Comment by jharris4** [comment]
Thank you for your work on this!

I haven't had much time to play with Webpack 4 yet, but hope to try it out soon! :-)

I'll release a new version shortly with these changes.

**Comment by jharris4** [comment]
Released in version 1.0.4

**Comment by macku** [comment]
Cool, thanks! 👍

**Comment by piuccio** [comment]
I updated to `1.0.4` but I'm still seeing the error, maybe my configuration is broken?

```js
    new CopyWebpackPlugin([
      { from: 'node_modules/whatever_project/reset.css', to: OUTPUT_PATH },
    ]),
    new HtmlWebpackIncludeAssetsPlugin({
      assets: ['reset.css'],
      append: false, // prepend
      hash: true,
    }),
```

And this is the error message

```
ERROR in   TypeError: Cannot read property 'publicPath' of undefined
  
  - index.js:236 onBeforeHtmlGeneration
    [project]/[html-webpack-include-assets-plugin]/index.js:236:34
  
  
  - new Promise
  
  
  - Hook.js:35 AsyncSeriesWaterfallHook.lazyCompileHook [as _promise]
    [project]/[html-webpack-plugin]/[tapable]/lib/Hook.js:35:21
  
  - index.js:647 
    [project]/[html-webpack-plugin]/index.js:647:47
  
  - index.js:162 Promise.resolve.then.then.then.then.compilationResult
    [project]/[html-webpack-plugin]/index.js:162:36
  
  
  - next_tick.js:160 process._tickCallback
    internal/process/next_tick.js:160:7
```

You can see that I'm on `1.0.4` because the error mentions `onBeforeHtmlGeneration` which was added by #23 [here](https://github.com/jharris4/html-webpack-include-assets-plugin/pull/23/commits/3d1d1725a542493aa9992d689163885af76e2d8b#diff-168726dbe96b3ce427e7fedce31bb0bcR222)

**Pull request merged**
